### Get req
GET http://localhost:8000/docs

### x
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
    "email": "yash1@test.com",
    "password": "123456789",
    "userName": "test",
    "securityQuestions": [
    { "question": "What was your childhood nickname?", "answer": "Johnny  " },
    { "question": "What is the name of your favorite childhood friend?", "answer": "Doe" },
    { "question": "What is your favorite movie?", "answer": "Inception" }
  ]
}
###
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "email": "yash@test.com",
    "password": "khushbu123"
}

### 
POST http://localhost:8000/api/auth/refresh-token
Content-Type: application/json

{
"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTc4ODAwNTIsImV4cCI6MTc0OTQzNzY1MiwiYXVkIjoiNjY2MzU1MTY3ZWU2ZDk5OTZjMDMzN2Q2IiwiaXNzIjoicmVudHJpcHBsZS5jb20ifQ.UUmflSMsYa9ClAQZyfYHQoaaPnHc18jt-pb3WuVifFE"
}

###
POST http://localhost:8000/api/auth/forgot-password
Content-Type: application/json

{
    "email": "khush@test.com"
}

###
POST http://localhost:8000/api/auth/verify-security-answers
Content-Type: application/json

{
    "email": "khush@test.com",
    "securityQuestion": "What is the name of your favorite childhood friend?", 
    "securityAnswer": "Doe" 
}

###
POST http://localhost:8000/api/auth/reset-password
Content-Type: application/json

{
    "email": "yash@test.com",
    "newPassword": "khushbu123"
}

###
DELETE  http://localhost:8000/api/auth/logout
Content-Type: application/json

{
    "email": "khush@gmail.com"
}


