### Get req
GET http://localhost:8000/docs

### x
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
    "email": "yash1@test.com",
    "password": "12345678",
    "userName": "test"
}
###
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "email": "ya@test.com",
    "password": "1235678"
}

### 
POST http://localhost:8000/api/auth/refresh-token
Content-Type: application/json

{
"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTc4ODAwNTIsImV4cCI6MTc0OTQzNzY1MiwiYXVkIjoiNjY2MzU1MTY3ZWU2ZDk5OTZjMDMzN2Q2IiwiaXNzIjoicmVudHJpcHBsZS5jb20ifQ.UUmflSMsYa9ClAQZyfYHQoaaPnHc18jt-pb3WuVifFE"
}
###
DELETE  http://localhost:8000/api/auth/logout
Content-Type: application/json

{  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTc4ODAwNTIsImV4cCI6MTc0OTQzNzY1MiwiYXVkIjoiNjY2MzU1MTY3ZWU2ZDk5OTZjMDMzN2Q2IiwiaXNzIjoicmVudHJpcHBsZS5jb20ifQ.UUmflSMsYa9ClAQZyfYHQoaaPnHc18jt-pb3WuVifFE"
}
