version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://mongo:27017
      - PORT=8000
      - NODE_ENV=development
      - DB_NAME=rentripplemongo
      - ACCESS_TOKEN_SECRET=b20143ec814d7ce470e55614732cf0168dbf5dc39d0fc470cecf783914f78b31
      - REFRESH_TOKEN_SECRET=45c5ea83abde2252abae9b47ebe4e61a985e8b7c2b68886c9f79091db86ddeed
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
  
volumes:
  mongo-data:
